services:
  - type: web
    name: finreg-rag-api
    runtime: python
    pythonVersion: "3.11"
    buildCommand: pip install --upgrade pip && pip install -r requirements-prod.txt
    startCommand: uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false